version: "3.4"

services:
  frontend:
    build: ./train-me-fe
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - backend
    networks:
      - trainme

  backend:
    build: ./train-me-be
    depends_on:
      - database
    networks:
      - trainme
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/train_me?autoReconnect=true

  database:
    image: mysql:8.0.24
    command: --init-file /data/application/init.sql
    volumes:
      - ./config/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: train_me
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
    networks:
      - trainme
networks:
  trainme:
